server:
  port: 8080

spring:
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    # excluded-view-names:
    # template-resolver-order:
    # view-names:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testschema
    username: Golio
    password: 112gendalf
#    url: jdbc:mysql://mysql3000.mochahost.com:3306/dudnik_iscare?useTimezone=true&serverTimezone=UTC
#    username: dudnik_golio
#    password: AzCompanY2019




logging:
  level:
    root: WARN
    com.memorynotfound: DEBUG
    org.springframework.sql: DEBUG
    org.springframework.type: TRACE
    org.springframework.web: INFO
    org.springframework.security: INFO